### ISSUE TITLE
Create haze list

### ISSUE THREAD

**Issue by laurenball** [laurenball/Steven#10]
Just like the [affirmations](https://github.com/laurenball/Steven/blob/master/data/affirmations.yml) list, the haze list will house insults to be lobbed at any user configured with the `:haze` action

**Comment by brooksbecton** [comment]
I think this one may be done. 
Is there anything else that Steven needs for hazing?

**Comment by laurenball** [comment]
nope, just forgot to close the issue. still figuring out the workflow.
thanks!
