### ISSUE TITLE
No info about installing dependecies in README

### ISSUE THREAD

**Issue by brooksbecton** [laurenball/Steven#12]
I was able to get the bot running but I had install **bundler** and then run `bundler install` to install the dependencies. 

Since some people working on this may not be as familiar with Ruby or installing dependencies, I think we should add information about installing dependencies to the README

**Comment by laurenball** [comment]
@brooksbecton do you want to do that?

**Comment by brooksbecton** [comment]
I believe this one is finished :feelsgood:

**Comment by laurenball** [comment]
u rite
