### ISSUE TITLE
Respond to name

### ISSUE THREAD

**Issue by laurenball** [laurenball/Steven#17]
Steven should reply when someone mentions him

**Comment by brooksbecton** [comment]
I GOT DIS!

**Comment by laurenball** [comment]
😎 excellent, thank you.

I was also originally intending to get him to respond when using the steven emoji, but was having a hell of a time parsing custom emojis using discordrb... if you're feeling spicy @brooksbecton

**Comment by laurenball** [comment]
resolved by #19
