### ISSUE TITLE
Current user lookup will fail if a username is an integer

### ISSUE THREAD

**Issue by Jerrgree** [laurenball/Steven#23]
The current implementation to locate a user will assume that input is a User ID if the argument is an integer. However, it is possible to have integer usernames.

When the provided user information is an integer and a search by ID does not return any information, the bot should search by username before failing.

![image](https://user-images.githubusercontent.com/10146723/46588227-37667c00-ca5e-11e8-9c3a-da37567c142f.png)

**Comment by brooksbecton** [comment]
I've done all of my bot user identification by user ID, because someone could have the exact same username. 

How would we handle a collision? 

I think that is why it assumes it's a user's ID

**Comment by Jerrgree** [comment]
The bot already allows for usernames, and in the event of a username collision prompts for an ID instead.

In the solution that I have provided, if it is an integer and a user with that ID exists on the server, it will always take the ID. Only if a user with no ID exists does it do a search on the username.
