### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by laurenball** [laurenball/Steven#42]
[README.md](https://github.com/laurenball/Steven/blob/master/README.md) is out of date: 
  - include missing commands
    - [ ] !removeaction - This is **owner only** command
    - [ ] !help
    - [ ] !display
  - include missing event triggers (in the 'hooks' section of the readme)
    - [ ] mentions

[CONTRIBUTING.md](https://github.com/laurenball/Steven/blob/master/CONTRIBUTING.md) is out of date:
  - [ ] New branches should be created from `develop`
  - [ ] Ready to review branches should be up to date with `develop`
  - [ ] Remove label part step

**Comment by Annysah** [comment]
Hello, I would love to work on this documentation.

**Comment by cam-ball** [comment]
go for it @Annysah! happy hacktoberfest!
Let me know if you have any questions!

**Comment by Annysah** [comment]
Am I to include the missing commands and the missing event triggers to the owner-only command

**Comment by cam-ball** [comment]
great question @Annysah! I updated the issue description, but at a high level, only the `!removeaction` command is owner only in this list.

The missing event trigger isn't a command, but a 'hook,' which I also added to the text.
Does that clarify enough?

**Comment by Annysah** [comment]
Yes, one more question what about the !help and !display where will they belong?

**Comment by cam-ball** [comment]
:facepalm: I really thought this was a better formed issue than it was, sorry for all of this not being more obvious @Annysah!

I guess there isn't a section for that yet! Why don't we make a new section above 'Owner-only commands'? Maybe something like
 ```
#### Commands
Accessible by any user on any server where Steven is present
[ `!help` and `!display` command info ]
```

the wording there doesn't need to be exact, so feel free to change it if you think something else makes sense!

**Comment by cam-ball** [comment]
also, in case you're not able to run the bot on your own to see what the commands to, here are some screenshots of the `!help` and `!display` commands in action.

you can probably guess what `!removeaction` does, based on the `!addaction` information :)

![Screenshot from 2020-10-02 14-28-21](https://user-images.githubusercontent.com/16344962/94957420-b363f500-04bb-11eb-8a8a-58ef29014b8d.png)
![Screenshot from 2020-10-02 14-28-35](https://user-images.githubusercontent.com/16344962/94957421-b3fc8b80-04bb-11eb-893b-2b6bb40b80fa.png)

**Comment by cam-ball** [comment]
hey @Annysah, slightly unrelated to this issue, but there [have been some changes to the hacktoberfest ruleset](https://hacktoberfest.digitalocean.com/details), specifically surrounding what repositories are 'valid' entries for the event. I have updated this repo to be compliant (so any PR you make here will count towards contributions towards the event), but wanted to let you know that the rules had changed just in case you hadn't seen
